version: '3'

services:
  database:
    image: postgres:10.5
    container_name: dix_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - .docker/postgres:/var/lib/postgres
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: dix_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - .docker/redis/redis-data:/var/lib/redis
      - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - app-network

  # api:
  #   build:
  #     context: ./
  #     dockerfile: .docker/node/Dockerfile
  #   container_name: dix_api
  #   restart: unless-stopped
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - "3333:3333"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
